#!/bin/bash
#
# This script will update the current session look based on Xresources values.
#
set -x

if [ "$#" -ne 1 ]; then
    echo "Usage: regolith-look <command>"
    echo "Commands: refresh"
    exit 1
fi

COMMAND=$1

refresh() {
    # File Locations - Optional User Overrides
    USER_XRESOURCE_FILE="$HOME/.Xresources-regolith"

    # File Locations - System Defaults
    DEFAULT_XRESOURCE_FILE="/etc/regolith/styles/root"

    # Avoid loading an early version of the Regolith Xresource file
    BAD_XRES_HASH="6797c718fc4767653878ef9db5f68017"
    HASH=`md5sum $USER_XRESOURCE_FILE | cut -d " " -f1`
    if [ -f "$USER_XRESOURCE_FILE" -a "$HASH" != "$BAD_XRES_HASH" ]; then
        xrdb -merge $USER_XRESOURCE_FILE 
    else
        xrdb -merge $DEFAULT_XRESOURCE_FILE
    fi

    UPDATE_FLAG_DIR="$HOME/.config/regolith/flags"
    UI_REFRESH_FLAG_FILE="$UPDATE_FLAG_DIR/ui-fingerprint"
    KNOWN_FINGERPRINT=$(<$UI_REFRESH_FLAG_FILE)
    # Generate hash from Xresources that don't begin with 'X'.
    CURRENT_FINGERPRINT=$(xrdb -query | grep -v ^X | md5sum | cut -d' ' -f1)
    if [[ $KNOWN_FINGERPRINT != $CURRENT_FINGERPRINT ]]; then
        # Set the theme from Xresources values.
        gsettings set org.gnome.desktop.interface gtk-theme "`xrescat gnome.gtk.theme Adwaita`"
        gsettings set org.gnome.desktop.wm.preferences theme "`xrescat gnome.wm.theme Adwaita`"
        gsettings set org.gnome.desktop.interface icon-theme "`xrescat gnome.icon.theme Adwaita`"

        # Set the wallpaper
        gsettings set org.gnome.desktop.background picture-uri "file:///usr/share/backgrounds/regolith-default.jpg"

        # Save current fingerprint to avoid unnecessary configuration.
        echo $CURRENT_FINGERPRINT > $UI_REFRESH_FLAG_FILE

        # restart i3-wm after merging Xresources
        i3-msg restart
    fi
}

if [ "$COMMAND" == "refresh" ]; then
    refresh
else 
    echo "Unrecognized command: $COMMAND"
    exit 1
fi
