ayu-mirage-regolith/color /etc/regolith/styles/ayu-mirage-regolith
ayu-mirage-regolith/typeface /etc/regolith/styles/ayu-mirage-regolith
ayu-mirage-regolith/theme /etc/regolith/styles/ayu-mirage-regolith
ayu-mirage-regolith/root /etc/regolith/styles/ayu-mirage-regolith
ayu-mirage-regolith/rofi.rasi /etc/regolith/styles/ayu-mirage-regolith
ayu-mirage-regolith/joel-filipe-unsplash.jpg /usr/share/backgrounds
ayu-mirage-regolith/ayu-mirage-regolith.xml /usr/share/gnome-background-properties